# Generated by Django 6.0 on 2026-09-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=50)),
                ('attendance', models.FloatField()),
                ('python_score', models.FloatField()),
                ('sql_score', models.FloatField()),
                ('ml_score', models.FloatField()),
                ('final_mark', models.FloatField()),
            ],
        ),
    ]
